# Generated by Django 5.1.1 on 2024-10-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_customuser_user_type_caretaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caretaker',
            name='experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='successful_bookings',
            field=models.IntegerField(null=True),
        ),
    ]
