# Generated by Django 5.1.1 on 2024-10-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_servicelisting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceListing',
        ),
    ]
