# Generated by Django 5.1.1 on 2024-11-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servlist', '0003_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
