# Generated by Django 5.1.1 on 2024-11-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servlist', '0005_remove_booking_book_status_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
