# Generated by Django 5.1.1 on 2024-11-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servlist', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking', 'Booking'), ('status', 'Status')], default='booking', max_length=50),
        ),
    ]
