# Generated by Django 5.1.1 on 2024-11-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servlist', '0006_notification_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='book_status',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('canceled', 'Canceled'), ('finished', 'Finished')], max_length=50),
        ),
    ]
