# Generated by Django 5.1.1 on 2024-11-29 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servlist', '0008_message_recipient_alter_message_sender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
