# Generated by Django 5.1.1 on 2024-12-01 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servlist', '0015_alter_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
    ]
