# Generated by Django 5.1.1 on 2024-12-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servlist', '0005_remove_booking_book_status_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
