# Generated by Django 5.1.1 on 2024-12-02 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servlist', '0006_booking_finish_date'),
        ('servlist', '0016_remove_message_sender'),
        ('servlist', '0017_message_sender'),
    ]

    operations = [
    ]
