# Generated by Django 5.1.1 on 2024-12-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servlist', '0017_merge_20241202_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
