# Generated by Django 5.1.1 on 2024-12-02 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servlist', '0018_merge_20241202_1140'),
        ('servlist', '0018_message_sender'),
    ]

    operations = [
    ]
