# Generated by Django 5.1.1 on 2024-12-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servlist', '0019_merge_0018_merge_20241202_1140_0018_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
