# Generated by Django 5.1.1 on 2024-10-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelisting',
            name='comment',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
