# Generated by Django 5.1.1 on 2024-11-29 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0002_alter_adminmessage_sender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminMessage',
        ),
    ]
